import { StyleSheet } from "react-native";
import { COLORS } from "../../../Constants/COLORS";

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    height: "100%",
  },
  headerText: {
    color: COLORS.font,
    fontSize: 25,
    marginHorizontal: 10,
    marginVertical: 10,
    alignSelf: "center",
    textAlign: "center",
  },
  headerText2: {
    color: COLORS.font,
    fontSize: 15,
    marginTop: 20,
    marginHorizontal: 10,
    alignSelf: "center",
    textAlign: "center",
  },
  text: {
    color: COLORS.font,
    fontSize: 16,
    marginHorizontal: 10,
    alignSelf: "center",
    textAlign: "center",
  },
  cafeName: {
    maxWidth: 210,
    alignSelf: "flex-start",
    fontSize: 30,
    fontWeight: "bold",
    color: COLORS.font,
    backgroundColor: COLORS.tertiary,
    borderTopRightRadius: 30,
    borderBottomRightRadius: 30,
    paddingStart: 10,
    paddingEnd: 30,
    paddingVertical: 15,
    marginTop: 20,
  },
  centeredView: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modalClose: {
    flex: 1,
    margin: 3,
    backgroundColor: "transparent",
    paddingHorizontal: "100%",
  },
  modalView: {
    height: 500,
    width: "95%",
    backgroundColor: COLORS.primary,
    borderTopEndRadius: 20,
    borderTopStartRadius: 20,
    padding: 10,
    shadowColor: COLORS.font_secondary,
  },
  modalText: {
    fontWeight: "bold",
    margin: 3,
    color: COLORS.font,
    backgroundColor: COLORS.secondary,
    paddingHorizontal: 120,
    paddingVertical: 2,
    borderRadius: 20,
  },
  rating: {
    alignSelf: "flex-start",
    fontSize: 12,
    fontWeight: "bold",
    color: COLORS.font,
    backgroundColor: COLORS.secondary2,
    borderRadius: 30,
    paddingHorizontal: 10,
    paddingVertical: 10,
    marginTop: 20,
    marginStart: -20,
  },
  count: {
    alignSelf: "flex-start",
    textAlign: "center",
    fontSize: 12,
    fontWeight: "bold",
    color: COLORS.font,
    backgroundColor: COLORS.primary,
    borderRadius: 100,
    borderColor: COLORS.font,
    borderWidth: 1,
    padding: 5,
    marginStart: -20,
  },
  Button2: {
    fontSize: 15,
    color: COLORS.font,
    backgroundColor: COLORS.tertiary,
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 10,
    marginEnd: 5,
  },
  Button3: {
    fontSize: 25,
    color: COLORS.font,
    backgroundColor: COLORS.tertiary,
    borderRadius: 30,
    paddingHorizontal: 20,
    paddingVertical: 10,
    marginTop: 10,
    marginEnd: 5,
  },
  image: {
    alignSelf: "center",
    width: 156.5,
    height: 160,
    marginTop: 10,
    marginEnd: 25,
    paddingHorizontal: 5,
  },

  image2: {
    justifyContent: "center",
    alignItems: "center",
    width: 100,
    height: 100,
    marginBottom: 5,
    borderRadius: 40,
  },
});

export default styles;
